name: Python package

on: [push]

jobs:

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: isort
        uses: jamescurtin/isort-action@master
      - name: flake8
        uses: py-actions/flake8@v2

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Install Gurobi license
        shell: bash
        env:
          WLSLICENSE: ${{ secrets.WLSLICENSE }}
        run: |
          mkdir -p /opt/gurobi
          echo "$WLSLICENSE" > /opt/gurobi/gurobi.lic
      - name: Test with pytest
        run: |
          pytest tests/test_cgal.py
      - name: Archive test plots
        uses: actions/upload-artifact@v3
        with:
          name: test_plots
          path: outputs/test_results/
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: test_plots
          path: test_plots
      - name: Set up Apache server
        uses: khan/apache-server@v1.0.1
        with:
          httpd-version: 2.4
          httpd-conf: |
            DocumentRoot /var/www/html
            <Directory /var/www/html>
              Options Indexes FollowSymLinks MultiViews
              AllowOverride All
              Require all granted
            </Directory>
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test_plots
          path: test_plots
          if-no-files-found: error
          retention-days: 30
